name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make run.sh executable
        run: |
          chmod +x hw_copy/run.sh
          chmod +x hw_vol/run.sh

      # Test for hw_copy
      - name: Build and Run hw_copy
        run: |
          echo "=== Testing hw_copy ===" > result.txt
          cd hw_copy
          ./run.sh >> ../result.txt
          cd ..

      # Test for hw_vol
      - name: Build and Run hw_vol
        run: |
          echo "=== Testing hw_vol ===" >> result.txt
          cd hw_vol
          ./run.sh >> ../result.txt
          cd ..

      # Upload the results as an artifact
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: docker-test-results
          path: result.txt

